# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: screenshot.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'screenshot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10screenshot.proto\x12\nscreenshot\"f\n\x15TakeScreenshotRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x14\n\x07\x65lement\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06script\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_elementB\t\n\x07_script\"\'\n\x16TakeScreenshotResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x32h\n\rScreenshotter\x12W\n\x0eTakeScreenshot\x12!.screenshot.TakeScreenshotRequest\x1a\".screenshot.TakeScreenshotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'screenshot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAKESCREENSHOTREQUEST']._serialized_start=32
  _globals['_TAKESCREENSHOTREQUEST']._serialized_end=134
  _globals['_TAKESCREENSHOTRESPONSE']._serialized_start=136
  _globals['_TAKESCREENSHOTRESPONSE']._serialized_end=175
  _globals['_SCREENSHOTTER']._serialized_start=177
  _globals['_SCREENSHOTTER']._serialized_end=281
# @@protoc_insertion_point(module_scope)
